### ISSUE TITLE
How to get a list of instantiated providers ?

### ISSUE THREAD

**Issue by stefaanMLB** [fjodor-rybakov/nestjs-dynamic-providers#19]
I'm trying to use this library to create a plugin architecture.
I managed to get the dynamic loading working, but now need a list of the instantiated plugins to call `start()` and `stop()` methods.
However, `Reflect.getMetadata('providers', PluginModule)` returns the types, not the instance of the plugins.
How can I access the provider instances ?

**Comment by fjodor-rybakov** [comment]
Hi! All insances you can get from NestJS IoC container. For example: 

```ts
async function bootstrap() {
  await resolveDynamicProviders();
  const app = await NestFactory.createApplicationContext(AppModule);
  
  const classInstance = app.get(ClassType);
  
  await app.init();
}

bootstrap();
```

This library pass only class type to NestJS reflect metadata, then everything else is done by NestJS itself

**Comment by stefaanMLB** [comment]
Since this is a plugin system, the class type is not known or available in bootstrap or in any of the main app modules.
The idea is that children of a `PluginBase` class (`*.plugin.js` files) can be added dynamically (requiring just a restart to load a new plugin)

**Comment by fjodor-rybakov** [comment]
> Since this is a plugin system, the class type is not known or available in bootstrap or in any of the main app modules. The idea is that children of a `PluginBase` class (`*.plugin.js` files) can be added dynamically (requiring just a restart to load a new plugin)

You will not be able to dynamically add metadata, since NestJS only introspects all method metadatas from all decorators once at startup.

In your case you can only interact only with NestJS IoC container directly or you need to somehow run metadata introspection over and over again.

**Comment by stefaanMLB** [comment]
I solved the problem now by distributing a list into which every plugin adds itself, but I don't like the solution very much.  Any ideas how this can be approved ?

In the module:
```ts
  providers: [
    // ...
    {
      provide: 'PLUGIN_LIST',
      useValue: [] as Plugin[],
    },
  ],
```

In the plugin base:
```ts
class PluginBase {
  constructor(
    //...
    pluginList: Plugin[],
  ) {
    pluginList.push(this)
//...
  }
}
