### ISSUE TITLE
How to debug it?

### ISSUE THREAD

**Issue by felinto-dev** [fjodor-rybakov/nestjs-dynamic-providers#2]
Hey!

Awesome library!
I'm trying to use it but it doesn't work as planned. Looks like my providers weren't imported. Is there any way I can check which providers have been imported to see if the package is working as it should?

**Comment by fjodor-rybakov** [comment]
Hi! If you want to know which providers have been added do the following:

Execute this after `await resolveDynamicProviders()`

To get module providers
```typescript
console.log(Reflect.getMetadata('providers', SomeYourModuleType))
```

To get module exports
```typescript
console.log(Reflect.getMetadata('exports', SomeYourModuleType))
```

You can also see how this is done in the tests
