### ISSUE TITLE
[Feature] Add support to monorepo apps

### ISSUE THREAD

**Issue by felinto-dev** [fjodor-rybakov/nestjs-dynamic-providers#6]
https://docs.nestjs.com/cli/monorepo#workspace-projects

![image](https://user-images.githubusercontent.com/32253743/143224201-5c193dc7-c76a-4a30-8861-bd4d710f08aa.png)

When I am using monorepo apps where has only single file InjectDynamicProviders do not work as intended.

**Comment by fjodor-rybakov** [comment]
Provide more information about your problem. `@InjectDynamicProviders('main.js')` doesn't work?

**Comment by fishuke** [comment]
I can relate to this problem, it doesn't work with monorepos.

**Comment by fjodor-rybakov** [comment]
Nest monorepo uses webpack under the hood. Webpack by default make tree shaking(this removes unused imports). Try to find a plugin that allows you to add unused imports to a bundle.
